import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
opacity = 0.8

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
# family = "MesloLGS Nerd Font Mono"
family = "RobotoMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "RobotoMono Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "RobotoMono Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "MesloLGS Nerd Font Mono"
family = "RobotoMono Nerd Font"
style = "Regular"
